language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  email:
    recipients:
      - abhi_ap@hotmail.com
    on_success: always
    on_failure: always
